CLASSPATH=.:App/edu.berkeley.sbp.jar
JAVAC=javac -classpath ${CLASSPATH} -Xlint:unchecked

compile:
	${JAVAC} `find . -name '*.java'` 

clean:
	find . -name '*.class' | xargs rm

# vi:set noexpandtab:
