INSERT INTO country (id, cont_id, name, last_updated) VALUES ('2','1', "Albania – Republic of Albania", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('3','2', "Algeria – People's Democratic Republic of Algeria", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('4','1', "Andorra – Principality of Andorra", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('5','2', "Angola – Republic of Angola", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('6','2', "Anguilla", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('7','2', "Antigua and Barbuda", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('8','4', "Argentina – Argentine Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('9','0', "Armenia – Republic of Armenia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('10','5', "Australia – Commonwealth of Australia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('11','1', "Austria – Republic of Austria", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('12','0', "Azerbaijan – Republic of Azerbaijan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('13','0', "Bahamas The – Commonwealth of The Bahamas", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('14','0', "Bahrain – Kingdom of Bahrain", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('15','0', "Bangladesh – People's Republic of Bangladesh", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('16','0', "Barbados", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('17','1', "Belarus – Republic of Belarus", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('18','1', "Belgium – Kingdom of Belgium", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('19','1', "Belize", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('20','2', "Benin – Republic of Benin", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('21','0', "Bhutan – Kingdom of Bhutan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('22','4', "Bolivia – Republic of Bolivia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('23','1', "Bosnia and Herzegovina", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('24','2', "Botswana – Republic of Botswana", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('25','4', "Brazil – Federative Republic of Brazil", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('26','0', "Brunei – Negara Brunei Darussalam", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('27','1', "Bulgaria – Republic of Bulgaria", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('28','2', "Burkina Faso", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('29','2', "Burundi – Republic of Burundi", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('30','0', "Cambodia – Kingdom of Cambodia ", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('31','2', "Cameroon – Republic of Cameroon", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('32','3', "Canada", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('33','2', "Cape Verde – Republic of Cape Verde", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('34','2', "Central African Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('35','2', "Chad – Republic of Chad", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('36','4', "Chile – Republic of Chile", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('37','0', "China – People's Republic of China", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('38','4', "Colombia – Republic of Colombia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('39','2', "Comoros – Union of the Comoros", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('40','2', "Congo – Democratic Republic of the Congo", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('41','2', "Costa Rica – Republic of Costa Rica", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('42','2', "Côte d'Ivoire – Republic of Côte d'Ivoire", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('43','1', "Croatia – Republic of Croatia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('44','1', "Cuba – Republic of Cuba", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('45','0', "Cyprus – Republic of Cyprus", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('46','1', "Czech Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('47','1', "Denmark – Kingdom of Denmark", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('48','2', "Djibouti – Republic of Djibouti", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('49','2', "Dominica – Commonwealth of Dominica", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('50','2', "Dominican Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('51','0', "East Timor – Democratic Republic of Timor-Leste", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('52','4', "Ecuador – Republic of Ecuador", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('53','2', "Egypt – Arab Republic of Egypt", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('54','2', "El Salvador – Republic of El Salvador", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('55','2', "Equatorial Guinea – Republic of Equatorial Guinea", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('56','2', "Eritrea – State of Eritrea", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('57','1', "Estonia – Republic of Estonia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('58','2', "Ethiopia – Federal Democratic Republic of Ethiopia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('59','5', "Fiji – Republic of the Fiji Islands", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('60','1', "Finland – Republic of Finland", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('61','1', "France – French Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('62','2', "Gabon – Gabonese Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('63','2', "Gambia The – Republic of The Gambia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('64','0', "Georgia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('65','1', "Germany – Federal Republic of Germany", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('66','2', "Ghana – Republic of Ghana", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('67','1', "Greece – Hellenic Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('68','1', "Grenada", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('69','1', "Guatemala – Republic of Guatemala", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('70','2', "Guinea – Republic of Guinea", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('71','2', "Guinea-Bissau – Republic of Guinea-Bissau", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('72','4', "Guyana – Co-operative Republic of Guyana", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('73','4', "Haiti – Republic of Haiti", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('74','4', "Honduras – Republic of Honduras", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('75','0', "Hong Kong – Hong Kong Special Administrative Region of the People's Republic of China", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('76','1', "Hungary – Republic of Hungary", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('77','1', "Iceland – Republic of Iceland", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('78','0', "India – Republic of India", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('79','0', "Indonesia – Republic of Indonesia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('80','0', "Iran – Islamic Republic of Iran", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('81','0', "Iraq – Republic of Iraq", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('82','1', "Ireland - Republic of Ireland", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('83','0', "Israel – State of Israel", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('84','1', "Italy – Italian Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('85','1', "Jamaica", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('86','0', "Japan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('87','0', "Jordan – Hashemite Kingdom of Jordan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('88','0', "Kazakhstan – Republic of Kazakhstan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('89','2', "Kenya – Republic of Kenya", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('90','5', "Kiribati – Republic of Kiribati", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('91','0', "Korea North – Democratic People's Republic of Korea", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('92','0', "Kuwait – State of Kuwait", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('93','0', "Kyrgyzstan – Kyrgyz Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('94','0', "Laos – Lao People's Democratic Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('95','1', "Latvia – Republic of Latvia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('96','0', "Lebanon – Republic of Lebanon", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('97','2', "Lesotho – Kingdom of Lesotho", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('98','2', "Liberia – Republic of Liberia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('99','2', "Libya – Great Socialist People's Libyan Arab Jamahiriya", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('100','1', "Liechtenstein – Principality of Liechtenstein", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('101','1', "Lithuania – Republic of Lithuania", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('102','1', "Luxembourg – Grand Duchy of Luxembourg", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('103','1', "Macedonia – Republic of Macedonia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('104','2', "Madagascar – Republic of Madagascar", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('105','2', "Malawi – Republic of Malawi", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('106','0', "Malaysia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('107','0', "Maldives – Republic of Maldives", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('108','2', "Mali – Republic of Mali", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('109','1', "Malta – Republic of Malta", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('110','2', "Mauritania – Islamic Republic of Mauritania", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('111','2', "Mauritius – Republic of Mauritius", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('112','3', "Mexico – United Mexican States", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('113','5', "Micronesia – Federated States of Micronesia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('114','1', "Moldova – Republic of Moldova", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('115','1', "Monaco – Principality of Monaco", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('116','0', "Mongolia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('117','1', "Montenegro – Republic of Montenegro", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('118','2', "Morocco – Kingdom of Morocco", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('119','2', "Mozambique – Republic of Mozambique", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('120','0', "Myanmar – Union of Myanmar", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('121','0', "Nagorno-Karabakh – Nagorno-Karabakh Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('122','2', "Namibia – Republic of Namibia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('123','5', "Nauru – Republic of Nauru", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('124','0', "Nepal – State of Nepal", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('125','1', "Netherlands – Kingdom of the Netherlands", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('126','5', "New Zealand", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('127','5', "Nicaragua – Republic of Nicaragua", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('128','2', "Niger – Republic of Niger", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('129','2', "Nigeria – Federal Republic of Nigeria", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('130','1', "Norway – Kingdom of Norway", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('131','0', "Oman – Sultanate of Oman", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('132','0', "Pakistan – Islamic Republic of Pakistan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('133','5', "Palau – Republic of Palau", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('134','0', "Palestine – proposed State of Palestine", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('135','0', "Panama – Republic of Panama", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('136','5', "Papua New Guinea – Independent State of Papua New Guinea", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('137','4', "Paraguay – Republic of Paraguay", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('138','4', "Peru – Republic of Peru", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('139','0', "Philippines – Republic of the Philippines", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('140','1', "Poland – Republic of Poland", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('141','1', "Portugal – Portuguese Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('142','0', "Qatar – State of Qatar", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('143','1', "Romania", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('144','1', "Russia – Russian Federation", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('145','2', "Rwanda", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('146','2', "Saint Lucia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('147','2', "Saint Vincent and the Grenadines", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('148','5', "Samoa – Independent State of Samoa", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('149','1', "San Marino – Most Serene Republic of San Marino", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('150','0', "Saudi Arabia – Kingdom of Saudi Arabia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('151','2', "Senegal – Republic of Senegal", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('152','1', "Serbia – Republic of Serbia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('153','2', "Seychelles – Republic of Seychelles", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('154','2', "Sierra Leone – Republic of Sierra Leone", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('155','0', "Singapore – Republic of Singapore", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('156','1', "Slovakia – Slovak Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('157','1', "Slovenia – Republic of Slovenia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('158','5', "Solomon islands", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('159','2', "Somalia", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('160','2', "South Africa – Republic of South Africa", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('161','1', "Spain – Kingdom of Spain", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('162','0', "Sri Lanka – Democratic Socialist Republic of Sri Lanka", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('163','0', "St. Kitts & Nevis", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('164','0', "St. Vincent and the Grenadines", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('165','2', "Sudan – Republic of the Sudan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('166','4', "Suriname – Republic of Suriname", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('167','2', "Swaziland – Kingdom of Swaziland", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('168','1', "Sweden – Kingdom of Sweden", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('169','1', "Switzerland – Swiss Confederation", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('170','0', "Syria – Syrian Arab Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('171','0', "Taiwan – Republic of China", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('172','0', "Tajikistan – Republic of Tajikistan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('173','2', "Tanzania – United Republic of Tanzania", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('174','0', "Thailand – Kingdom of Thailand", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('175','2', "Togo – Togolese Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('176','5', "Tonga – Kingdom of Tonga", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('177','5', "Trinidad and Tobago – Republic of Trinidad and Tobago", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('178','2', "Tunisia – Tunisian Republic", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('179','0', "Turkey – Republic of Turkey", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('180','0', "Turks and Caicos Islands", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('181','0', "Turkmenistan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('182','5', "Tuvalu", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('183','2', "Uganda – Republic of Uganda", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('184','1', "Ukraina", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('185','0', "United Arab Emirates", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('186','1', "United Kingdom – United Kingdom of Great Britain and Northern Ireland", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('187','3', "United States – United States of America", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('188','4', "Uruguay – Eastern Republic of Uruguay", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('189','0', "Uzbekistan – Republic of Uzbekistan", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('190','5', "Vanuatu – Republic of Vanuatu", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('191','4', "Venezuela – Bolivarian Republic of Venezuela", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('192','0', "Vietnam – Socialist Republic of Vietnam", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('193','0', "Yemen – Republic of Yemen", 'NOW()');
INSERT INTO country (id, cont_id, name, last_updated) VALUES ('194','2', "Zambia – Republic of Zambia", 'NOW()');
