INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '4', "Clau Digital (catala)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '6', " Education department\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '8', "Educ.ar (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '10', " Science and Training\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '11', " the Arts and Culture (English / German / French)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '14', "Edunet (Arabic)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '16', " Youth Affairs & Sports\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '18', " <a href='http://www.deped.gov.ph/&amp;usd=2&amp;usg=ALhdy2-rWwtuZLgwdg9RCgaxUFk7RzQqsA'><a href='http://www.ed.gov/&amp;usd=2&amp;usg=ALhdy29hdvn66RuURXi-MvtDE-jWNlTYJA'>Department of Education</a> </a>(Flemish / English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '19', "Ceducar (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '22', "EducaBolivia  (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '24', "<a href='http://thinktankthuto.org/&amp;usd=2&amp;usg=ALhdy2-voKnukPWiu6YcQ-FbnJlZknVqGg'>Thuto Net</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '25', "Portal de Conteúdos Educacionais do MEC (Portuguese) ");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '27', "<a href='http://www.schools.ac.cy/&amp;usd=2&amp;usg=ALhdy2-l8emqS5C1hI5c2fKkn6aAmM3pKw'>Educational Portal </a>for students (bulgarian)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '28', "TICE (Technologies de l’Information et de la Communication pour l’Enseignement TICE)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '28', " supérieur et de la recherche scientifique (French)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '30', " Youth and Sports (English/Khmer) \"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '36', "Educar (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '36', "Portal Pinguino (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '38', "Colombia Aprende  (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '41', "Educatico  (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '41', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '43', " Education and Sports. (Croatian / English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '44', "<a href='http://www.rimed.cu/&amp;usd=2&amp;usg=ALhdy28A2k6mOyB8lfWfbA83vx0yCgmmNw'>Cubaeduca</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '45', "<a href='http://www.schools.ac.cy/&amp;usd=2&amp;usg=ALhdy2-l8emqS5C1hI5c2fKkn6aAmM3pKw'>Educational Portal </a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '46', " Youth and Sport (Czech / English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '49', " Human Resource Development");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '50', "Educando (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '50', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '52', "Educar (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '53', "Educative portal (Arab)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '54', "Mi Portal (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '54', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '56', " temporarily down)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '58', "<a href='http://www.moe.gov.et/etep/&amp;usd=2&amp;usg=ALhdy2-lhdbdVtTf-bBTU0Sl7V9uZP3svQ'>Teachers education portal</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '62', " de la recherche");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '66', "<a href='http://www.moess.gov.gh/studentportal.htm&amp;usd=2&amp;usg=ALhdy29Yk7AoYXYhY_u5oWmKtijvNz1Aew'>Student portal</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '69', "Portal Educativo (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '69', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '74', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '76', "<a href='http://www.sulinet.hu/&amp;usd=2&amp;usg=ALhdy2_gQMkV44icyzDJez9j9NqlnQ7m0g'>Sulinet</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '77', " Science and Culture (Icelandic / Swedish / English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '78', "<a href='http://www.teachersofindia.org/&amp;usd=2&amp;usg=ALhdy29j_Z-HwXWTlFoNf3PC3KKRBAVBLg'>Teacher’s Portal</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '79', " English) \"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '82', "<a href='http://www.teachnet.ie/&amp;usd=2&amp;usg=ALhdy29ofVScnVimju52RiSlRXR7if8czw'>Teachnet </a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '83', " Culture and Sports (Hebrew / English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '84', "Ministero di Pubblica Istruzione (Italian)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '85', " Youth and Culture (English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '86', " Culture");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '88', "/ Kazakh / Russian)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '89', "\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '91', " science and technology  (English / Korean)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '102', "<a href='http://www.myschool.lu/&amp;usd=2&amp;usg=ALhdy28xMe0XVYsK1mbhGMz0-_JVTPSZ7A'>Myschool</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '104', " Ministère de l’Enseignement Supérieur et de la Recherche Scientifique. (French)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '108', " de L’Alphabétisation et des Langues Nationales (French)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '109', "<a href='http://www.tci-educationdepartment.tc/&amp;usd=2&amp;usg=ALhdy2-gO3YxZC22f2U_yg1RwYSQvt9UAQ'>Ministry of Education</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '111', " Culture & Human Resources\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '112', "Se piensa (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '112', "Enciclomedia (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '114', " / English / Russian)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '115', " de la Jeunesse et des Sports (French)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '116', " Culture and Science (Mongolian) \"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '118', " de l\' Enseignement Supérieur");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '125', "<a href='http://www.kennisnet.nl/&amp;usd=2&amp;usg=ALhdy29ifZBrQYFOojycvx_vqLQUT8Eoww'>Kennisnet</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '126', "Te kete Ipurangi (English / maori)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '127', "Portal Educativo (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '127', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '130', " Bokmal");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '131', "<a href='http://www.schools.ac.cy/&amp;usd=2&amp;usg=ALhdy2-l8emqS5C1hI5c2fKkn6aAmM3pKw'>Educational Portal </a>(Arabic/english)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '135', "Educa Panama  (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '135', "Ceducar (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '137', "Portal educativo Arandu rape  (Spanish / Guarani)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '138', "Huascaran (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '138', "Peru educa (spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '139', "<a href='http://ischools.wikispaces.com/&amp;usd=2&amp;usg=ALhdy2-Zf1qQFlP2l5i9HmOGXuEY14Q4Tw'>iSchools-CeC</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '141', "MaisEscola.pt (Portuguese, under development)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '141', " Technology and Higher Education (Portuguese)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '142', "<a href='http://www.knet.edu.qa/&amp;usd=2&amp;usg=ALhdy2_s12vo4CWEMiL1gHH_ONtCUSSBiQ'>Knowledge net</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '142', "<a href='http://www.elearning.ictqatar.qa/&amp;usd=2&amp;usg=ALhdy2-2cRFCNK2771XWY83OOhriN88uIw'>e-learning portal </a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '143', " research and youth (Romanian)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '144', "Auditorium (russian)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '146', " Human Resource Development");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '148', " Sports & Culture \"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '149', " l\'Univrsità");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '150', " Technical and Vocational Education (English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '155', "<a href='http://schoolbag.sg/&amp;usd=2&amp;usg=ALhdy29V04Ky7QYvCDtOvk0-_fd1ngpOeQ'>Schoolbag</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '155', "<a href='http://www.edumall.sg/&amp;usd=2&amp;usg=ALhdy2_dWaKsTdRqcasap2X-Ioru3IQH4Q'>Edumall</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '157', " <a href='http://www.scienceandtechnology.go.ke/&amp;usd=2&amp;usg=ALhdy2_g3k2UeAoKtdQlxQskUuTDnwAPIA'>Science and Technology</a> (Slovenian / English)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '158', "<a href='http://www.peoplefirst.net.sb/DLCP/default.htm&amp;usd=2&amp;usg=ALhdy2_bC7W8vItfmIKoblD6mXkwrTFKKA'>Distance Learning Centres Project</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '160', "<a href='http://www.thutong.org.za/&amp;usd=2&amp;usg=ALhdy28G0cQYeT22CfqFZvdAJXIwPwho3A'>Thutong</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '161', " Politica Social y Deporte (Spanish / Catalá / Vasc)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '169', "Educanet (German / Italian / English / French)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '169', "Educa.ch (German / Italian / English / French)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '173', "<a href='http://www.teachers.or.tz/&amp;usd=2&amp;usg=ALhdy2-uQmBp6aOgBj7LpCZ3CA68D1sxKQ'>Wakute</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '175', " Secondaire et de l\'Alphabétisation (MEPSA)\"");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '177', "<a href='http://www.moe.gov.tt/student_portal.html&amp;usd=2&amp;usg=ALhdy29b-QCdofAb-BXlrY9DczYCduOZAQ'><a href='http://www.moess.gov.gh/studentportal.htm&amp;usd=2&amp;usg=ALhdy29Yk7AoYXYhY_u5oWmKtijvNz1Aew'>Student portal</a> </a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '178', " French");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '185', "<a href='http://www.moe.gov.ae/English/pages/Studentsdefault.aspx&amp;usd=2&amp;usg=ALhdy2_kRvVlaS4wkfrDcxp8omUWj5HXDw'>Student’s portal</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '186', "<a href='http://www.teachernet.gov.uk/&amp;usd=2&amp;usg=ALhdy2__2fIz2pAnK7Tm1-la6yT11GqWdw'>Teachernet</a>");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '188', "Uruguay Educa (Spanish)");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '191', "Portal Educativo (Spanish) ");
INSERT INTO education_portal (id, country_id, website) VALUES(NULL, '191', "Red nacional de actualización docente mediante la informática y la telemática (spanish)");
